# Generated by Django 2.0.7 on 2018-07-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='movies',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Person'),
        ),
    ]
