# Generated by Django 2.0.7 on 2018-07-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20180709_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
