# Generated by Django 2.0.7 on 2018-07-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20180717_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
