# Generated by Django 2.0.7 on 2018-07-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.Movies'),
        ),
    ]
