# Generated by Django 2.0.7 on 2018-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='person',
        ),
        migrations.AddField(
            model_name='movies',
            name='isRented',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Assign',
        ),
    ]
