# Generated by Django 2.0.7 on 2018-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20180720_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
